version: '3'
volumes:
    fog05-meao-yaks:
    fog05-meao:

networks:
  netMEAO:
      external:
        name: fog05-meaonet

services:
  fog05-meao-yaks:
    image: fog05/yaks
    # ports:
    #   - "7887:7887"
    networks:
      - netMEAO
  fog05-meao:
    image: fog05/meao
    networks:
      - netMEAO
    environment:
      YAKS_HOST: fog05-meao-yaks
      YAKS_PORT: 7887
    ports:
      - "8071:8071"
    depends_on:
      - fog05-meao-yaks

